### ISSUE TITLE
allow users to define URLs they "own"

### ISSUE THREAD

**Issue by jcs** [jcs/lobsters#171]
When a user submits an article at a URL that matches that user's "owned" list, the story can display some kind of indicator that the author of the article is actually the user.

**Comment by harsha-mudi** [comment]
+1

**Comment by stig** [comment]
I think the "I am the author" checkbox suffices.

**Comment by harsha-mudi** [comment]
A simple "selfie", "ego-post" tag can also work.

A thread in lobste.rs [thread](https://lobste.rs/s/7wzwa3/how_about_a_selfie_tag/comments/ybv21k#c_ybv21k).

**Comment by stig** [comment]
It occurred to me also recently that a special tag could work. The beauty of that is that hiding by tag already is a thing, so if people don't like selfie-posts they can hide them.
