### ISSUE TITLE
Feature: Include Schema.org markup to email notifications.

### ISSUE THREAD

**Issue by brycied00d** [jcs/lobsters#174]
In looking through https://developers.google.com/gmail/actions/ I noticed that there's a "Comment" https://developers.google.com/gmail/actions/reference/types/Comment action. This would be a very cool feature to add to Lobste.rs' email notifications of comment replies, with relatively little work.

What do others think?

**Comment by jcs** [comment]
I don't use Gmail, so is this still a thing?

**Comment by brycied00d** [comment]
Yeah it's still a thing, and its integration into Google products is spreading (Google Now, Inbox, GMail, etc).

Here is Google's checklist for what needs to be done/in-place.  And yes a registration process is still required.
* Emails must be authenticated via DKIM or SPF *[Check, SPF]*
* The top-level domain (TLD) of the SPF check or DKIM signature must match the TLD of your From: email address.
   e.g. if you use From: foo@bar.com the DKIM or SPF must be for bar.com or sub.bar.com
   Gmail only checks the SPF on the domain of your Return-Path: email. If you only rely on SPF and not DKIM your Return-Path: email must match the TLD of your From: email.
  To quickly check if your SPF or DKIM settings are correct have a look at our Email Authentication help article.  *[Check, lobste.rs]*
* Emails must come from a static email address, e.g. foo@bar.com  *[Nope! Currently $user@lobste.rs]*
* Emails must follow the Gmail Bulk Sender Guidelines  *[Probably maybe?]*
* Consistent history of sending a high volume of mail from your domain (order of hundred emails a day minimum to Gmail) for a few weeks at least.  *[I couldn't answer this]*
* A very very low rate of spam complaints from users.  *[I hope so]*

**Comment by zg** [comment]
@brycied00d What benefits does it bring to folks who don't use Google products?

**Comment by jcs** [comment]
I don't think this is worth the changes required.
