### ISSUE TITLE
Option to show top-level comments only

### ISSUE THREAD

**Issue by stig** [jcs/lobsters#181]
[This thread](https://lobste.rs/s/5ovrc2/what_s_your_most_controversial_technical_opinion) makes me really wish for the ability to only show top-level comments, or at least distinguish top-level comments somehow so yo can quickly identify them while scanning down the list of comments. I'm usually more interested in the top-level comments than the discussions hanging off from each of them.

**Comment by BennyHallett** [comment]
I'm interested in implementing this feature if there are no objections?
