### ISSUE TITLE
provide comment tree lines

### ISSUE THREAD

**Issue by jcs** [jcs/lobsters#189]
On some long threads (especially on mobile) it can be hard to immediately tell which parent a child comment is in response to, so some very light colored tree lines might be helpful (as on the [user tree](https://lobste.rs/u)).

**Comment by daGrevis** [comment]
Maybe it's time to reconsider https://lobste.rs/s/m5dlun/comment_folding.

**Comment by jcs** [comment]
That could be added later, but it really has nothing to do with this.

**Comment by bentrevor** [comment]
Looks like this can be accomplished by just adding a `border-left` to `ol.comments`.  Something like `border-left: 1px dotted #ccc;` if you want it to look like Reddit.
