### ISSUE TITLE
Allow comments to include harmless raw HTML like <i>

### ISSUE THREAD

**Issue by roryokane** [jcs/lobsters#193]
I want to be able to write `<i>` in comments, to mark up italicized text that is not emphasis, such as the book name in `I read <i>Feet of Clay</i>`. Currently, Lobsters just escapes that so the text comes out as “I read \<i\>Feet of Clay\</i\>”.

The cause of this is [`extras/markdowner.rb` passing](https://github.com/jcs/lobsters/blob/cb850bd9e6ac1f5b68078db26293144b6097a253/extras/markdowner.rb#L10) the [`:filter_html` argument](http://www.rubydoc.info/github/davidfstr/rdiscount/RDiscount#filter_html-instance_method) to RDiscount, which disables output of raw HTML included in the source text.

Perhaps the reason you are using this filter is to prevent security issues or obnoxious markup by removing the ability to specify them with HTML. A better way to accomplish that, which preserves Markdown’s HTML feature, is to sanitize the HTML with a library after passing it through Markdown. I used [Sanitize](https://github.com/rgrove/sanitize) before, and it looks like would work for you. This might be all the configuration you need:

```ruby
html = Sanitize.fragment(html, Sanitize::Config.merge(Sanitize::Config::BASIC,
  :elements => Sanitize::Config::BASIC[:elements] + (opts[:allow_images] ? ['img'] : []),
))
```

You can look at [the definition of `Sanitize::Config::BASIC`](http://www.rubydoc.info/github/rgrove/sanitize/master/Sanitize/Config) to make sure you approve of its whitelist of tags.

As a bonus, `Sanitize::Config::BASIC` adds `rel="nofollow"` for you, so you can remove [your custom code for that](https://github.com/jcs/lobsters/blob/cb850bd9e6ac1f5b68078db26293144b6097a253/extras/markdowner.rb#L30-L31). You can stop [passing `:filter_styles`](https://github.com/jcs/lobsters/blob/cb850bd9e6ac1f5b68078db26293144b6097a253/extras/markdowner.rb#L10) to RDiscount. And if you wanted, you could make [your conversion of `h1`s to `strong`s](https://github.com/jcs/lobsters/blob/cb850bd9e6ac1f5b68078db26293144b6097a253/extras/markdowner.rb#L17-L18) more robust by using a Sanitize [transformer](https://github.com/rgrove/sanitize#transformers) instead.

**Comment by daGrevis** [comment]
Why don't you just use `_` to emphasize text? _\_Like this.\__

**Comment by roryokane** [comment]
@daGrevis 
Because `_` produces the [`<em>` tag](https://html.spec.whatwg.org/multipage/semantics.html#the-em-element), but I want the [`<i>` tag](https://html.spec.whatwg.org/multipage/semantics.html#the-i-element). There is a [semantic difference](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/em#%3Ci%3E_vs._%3Cem%3E). For example, if a screen reader reads my comment out loud, it shouldn’t speak the book title with stress emphasis; it should speak it normally.

Raw `<i>` or `<b>` in Markdown is also sometimes useful for marking up templates in `<code>` blocks. Like this:

> Run this command:
> 
> <pre><code>process-foo name=<i>your_name</i> dir=<i>your_project_root</i></code></pre>

**Comment by roryokane** [comment]
I ran into another situation where I needed this: writing a code block containing \` (backtick). In a discussion about Org mode and Markdown, I wanted to say something like “Markdown uses <code>`</code> to mark code.” 

```html
Markdown uses <code>`</code> to mark code.
```

But I had to leave the \` un-marked-up, because “`<code>`” was escaped.

**Comment by jcs** [comment]
Sorry, but I do not want the added security concerns of allowing HTML.  The tradeoffs don't really seem worth it.
