### ISSUE TITLE
cannot link to dotless and top-level domains

### ISSUE THREAD

**Issue by cnst** [jcs/lobsters#195]
I've tried submitting `http://uz/` as `URL`, but I'm getting an error message:

```
1 error prohibited this story from being saved

There were problems with the following fields:

    Url is not valid
```

I've tried adding a dot, `http://uz./`, and `Fetch Title` started to work, but the story still couldn't be submitted.

http://uz/
http://uz./

**Comment by jcs** [comment]
Considering Firefox won't even navigate there with a full direct URL in the address bar (it automatically tries uz.com), I don't think this is really a problem.

**Comment by cnst** [comment]
Hm, it works in my somewhat outdated SeaMonkey.  Typing "uz" gets me to "http://uz/".

**Comment by cnst** [comment]
Hm, it works in my somewhat outdated Mozilla SeaMonkey.  Typing "uz" gets me to "http://yz/".

I was also able to submit this as "http://uz./" to HN, although without the dot, it doesn't accept it, either.  https://news.ycombinator.com/item?id=9254109
