### ISSUE TITLE
Hide comments from specific users

### ISSUE THREAD

**Issue by wickedchicken** [jcs/lobsters#197]
Hi,

Much in the same way stories can be hidden, I'd like for comments by certain users to be hidden as well. Ideally this could show up as <comment by a hidden user> which could be clicked and expanded if desired.

The reason I am requesting this is that there are certain commenters whom I would like to avoid, but don't think should be outright banned from the site. A private block seems like a happy solution.

Thanks for lobste.rs, it's great!

**Comment by jcs** [comment]
That would break threading, so is it supposed to hide the entire thread under a blocked comment?

**Comment by kyrias** [comment]
You could possibly replace the comment with an empty dummy-comment, having the user listed as ignored.

**Comment by bconway** [comment]
+1. I've found an increasing number of users that inject their politics into every post they make and find myself avoiding discussions entirely.

**Comment by wickedchicken** [comment]
The UI I was imagining would be as follows (using ⋅⋅⋅ to signify indents, markdown doesn't seem to like spaces):

user1 2 hours ago | link | reply
An insightful comment.

⋅⋅⋅ [hidden] 16 minutes ago | unhide

⋅⋅⋅⋅⋅⋅ user1 4 minutes ago | link | reply
⋅⋅⋅⋅⋅⋅⋅⋅⋅Another insightful comment responding to the hidden one.

**Comment by pushcx** [comment]
I wrote a greasemonkey script for myself a while ago

```javascript
// ==UserScript==
// @name        Atheist Lobsters
// @namespace   http://lobste.rs/u/pushcx
// @description separation of church and sanity
// @include     https://lobste.rs/*
// @version     1
// @grant       none
// ==/UserScript==

domain = 'example.com';
username = 'example';

// hide stories
[].slice.call(document.querySelectorAll('.story a.domain[href="/search?q=domain:' + domain + '&order=newest"]')).forEach(function (el) { el.closest(".story").remove() });

// hide comments
[].slice.call(document.querySelectorAll('.comment a[href="/u/' + username + '"]')).forEach(function (el) { el.closest(".comment").remove() });
```

**Comment by crertel** [comment]
@wickedchicken @bconway have you considered just...ignoring...those posts? Also, you might want to link to some examples to show what you mean.

Adding additional echochamber features is probably not a great idea.

**Comment by bconway** [comment]
@crertel Thanks for the tip. Since I left the site over a year ago, it's probably safe for me to unsubscribe from this conversation.

**Comment by wickedchicken** [comment]
@crertel I originally made this request after scrolling through pages of comments made by a person who preferred the "wall of text" approach to discussion. This made it quite difficult to ignore the posts.

I've seen (and written) a few lengthy comments here and there, but I don't think long comments are a general problem in lobsters. I _have_ seen specific users overly rely on long comments, which is why I requested "hide specific users" and not "deal with the long comment problem" (which I imagine would be a much more involved discussion).

**Comment by crertel** [comment]
@wickedchicken ah, gotcha. @pushcx 's script is probably a good help for the moment then. :)

**Comment by danielcompton** [comment]
I've made a meta post for discussion about this here: https://lobste.rs/s/debnsq/hiding_comments_by_specific_users.

**Comment by jcs** [comment]
Sorry, but there didn't seem to be a lot of concensus around wanting this.

**Comment by untitaker** [comment]
I wrote uBlock filters for this purpose:

```
lobste.rs##.comments .comments_subtree:has(> .comment > .details > .byline > a[href="/u/baduser"])
```
