### ISSUE TITLE
Provide a feed of all comments

### ISSUE THREAD

**Issue by ap** [jcs/lobsters#202]
I’d like to follow all conversation on the site. Right now I’m subscribed via RSS, and I open both a link and its thread when I look at the feed and find something interesting, but often the stories are too new to have any (substantial, non-meta) comments. Generally this means that whatever discussion may later happen, I will never see it.

Looking at the Comments page, the aggregate comment volume of the entire site is low enough that I could well keep up with *all* discussion.

The only problem is, there is no aggregate comments feed.

**Comment by jcs** [comment]
https://lobste.rs/comments.rss

**Comment by ap** [comment]
Thank you!
