### ISSUE TITLE
Proxy Gravatars to avoid tracking

### ISSUE THREAD

**Issue by untitaker** [jcs/lobsters#204]
GitHub and other sites proxy images embedded in READMEs (e.g. Travis buttons), and did the same with Gravatars until they switched away from it. It would be nice if lobste.rs did the same, especially as Gravatars can't be turned off when viewing the profile of a user.

**Comment by jcs** [comment]
Sorry, but that's a huge undertaking for a small reward.

**Comment by untitaker** [comment]
I understand. Could you then make the user profile page respect my Gravatar settings instead?
