### ISSUE TITLE
Feature: Do something more useful with Poorly Tagged and Poorly Titled flagging

### ISSUE THREAD

**Issue by bconway** [jcs/lobsters#207]
I think something more useful could be done with the above two flags than simply subtracting points, without greatly increasing moderator load. I notice this most often with Poorly Tagged, where it's usually the case of a missing tag, such as "rant" or "satire."

Some examples:
- When Poorly Tagged is chosen, offer a pop-up list of possible tags with the current ones preselected. If X number of users in Y time choose the same set of tags (again, adding "rant", for example), update the tags.
- If a user editorializes a title (not unusual), offer a text box when choosing Poorly Titled. If X users copy-paste the *exact* same title, presumably from the article, update the title.

Obviously it would be possible to game these if someone _really_ wanted to deface a title with 10 shadow accounts, but it seemed like a good start.

**Comment by jcs** [comment]
The 'suggest' functionality is there now, but it needs the automated actions hooked up.

I think it should log a Moderation record when doing tag changes.

**Comment by bconway** [comment]
Cool, thanks!

**Comment by jcs** [comment]
Some minor tweaks may be necessary to the quorum size but I think this is more or less implemented.
