### ISSUE TITLE
/recent doesn't show hot stories

### ISSUE THREAD

**Issue by xcombelle** [jcs/lobsters#208]
As I had the happiness of one my story reach the front page, I discovered also that it disappeared of /recent page. It is still in /newest page. It is at least not what I expected of /recent page because before that I frequently used /recent to have all the fresh news not only the less interesting ones.

**Comment by jcs** [comment]
It clearly says this at the top of the page:

>  The newest stories with a random sampling of recently submitted stories that have not yet reached the front page.

**Comment by xcombelle** [comment]
It's clear when you read as "(The newest stories with a random sampling of recently submitted stories) that have not yet reached the front page."  not as "(The newest stories) with (a random sampling of recently submitted stories that have not yet reached the front page.) " (as I read it) but as I'm not a native speaker I don't know if this sentence is not clear or I'm just bad in English.
