### ISSUE TITLE
In Markdown, URLs in <…> have the period moved outside the link

### ISSUE THREAD

**Issue by roryokane** [jcs/lobsters#209]
### The symptoms

Try previewing a comment containing this markup (e.g. on [this story](https://lobste.rs/s/zw21z4/supreme_court_denies_google_appeal_on_oracle_suit)):

    <https://en.wikipedia.org/wiki/UNIX_System_Laboratories,_Inc._v._Berkeley_Software_Design,_Inc.>

What should be rendered:

> <https://en.wikipedia.org/wiki/UNIX_System_Laboratories,_Inc._v._Berkeley_Software_Design,_Inc.>

What Lobsters renders:

> <https://en.wikipedia.org/wiki/UNIX_System_Laboratories,_Inc._v._Berkeley_Software_Design,_Inc>.

The period at the end is moved outside of the link, breaking it. This is useful when autolinking, but not with explicit `<…>` links.

I can work around this by using `[…](…)` syntax instead, duplicating the URL:

    [https://en.wikipedia.org/wiki/UNIX_System_Laboratories,_Inc._v._Berkeley_Software_Design,_Inc.](https://en.wikipedia.org/wiki/UNIX_System_Laboratories,_Inc._v._Berkeley_Software_Design,_Inc.).

### The cause

The problem is probably [this part in `extras/markdowner.rb`](https://github.com/jcs/lobsters/blob/e0e8c9f484616f4f427aa4cd4a2fd3c6dc35df8a/extras/markdowner.rb#L20-L28), labeled “fix links that got the trailing punctuation appended to move it outside the link”. I know the problem is after [line 15](https://github.com/jcs/lobsters/blob/e0e8c9f484616f4f427aa4cd4a2fd3c6dc35df8a/extras/markdowner.rb#L15), because I confirmed that RDiscount 2.1.7.1 ([the version Lobsters uses](https://github.com/jcs/lobsters/blob/e0e8c9f484616f4f427aa4cd4a2fd3c6dc35df8a/Gemfile.lock#L85)) includes the period correctly when I try to parse `<…>` with RDiscount directly from `irb`, with the [same arguments](https://github.com/jcs/lobsters/blob/e0e8c9f484616f4f427aa4cd4a2fd3c6dc35df8a/extras/markdowner.rb#L10).

### The fix

RDiscount still wrongly includes the punctuation in links like

> I don't like <http://example.com/prices.> They are too expensive.

So you can’t just delete that punctuation-removal code.

To fix this bug, I think you have to run the filter before the Markdown is processed. In the filter, look for raw URLs in the text that are not part of a link (a harder task than just searching for `<a>` tags), and then explicitly wrap them with `<…>`s that exclude ending periods.

**Comment by jcs** [comment]
fixed by 6e6803f205
