### ISSUE TITLE
User statistics

### ISSUE THREAD

**Issue by zg** [jcs/lobsters#212]
This is a feature request.

Maybe have a page where it shows user statistics, i.e. highest karma, highest average, most stories/comments submitted. Though, the downside to this feature would bring on more potential abuse to manipulate the statistics.

**Comment by jcs** [comment]
https://lobste.rs/u?by=karma is there.  I guess some other sorting methods could be added.

**Comment by zg** [comment]
I'm guessing there would have to be a new condition [here](https://github.com/jcs/lobsters/blob/master/app/controllers/users_controller.rb#L25-L26) that involves the WHERE clause bringing in the [average_karma](https://github.com/jcs/lobsters/blob/master/app/models/user.rb#L93-L99) function.

**Comment by crertel** [comment]
@jcs mind if I take a crack at this?

**Comment by jcs** [comment]
go for it

**Comment by crertel** [comment]
What all do people want to see?

**Comment by zg** [comment]
Percentage of total karma that @pushcx has, for starters.

**Comment by pushcx** [comment]
My karma is currently 19428, so:
```
$ curl -s https://lobste.rs/u?by=karma | grep -o -e "^ *(.*)$" | grep -o -e "-*[0-9][0-9]*" | awk '{s+=$1} END {print s}' | awk '{print 19428/$1*100}'
8.36956
```

Two caveats:
1. jcs's karma is not visible, lowering the sum and increasing my percentage
2. the existence of folks with net negative karma makes me think the naive sum of user karma score makes this calculation unsound (imagine the site had two users: Alice has 2 karma, Bob has -1; what is Alice's percentage of total karma?)

**Comment by geocar** [comment]
Awk and grep can be combined:

    awk '/^ *\(/ { gsub(/[^0-9-]/,""); s+=$1; } END { print 19428/s*100 }'

As a possible suggestion to solving *2*, you can drop one character and take the sum magnitude, which will lower you to `8.35038`:

    awk '/^ *\(/ { gsub(/[^0-9]/,""); s+=$1; } END { print 19428/s*100 }'

Perhaps more interesting than arithmetic means, would be percentile:

    awk '/^ *\(/ { gsub(/[^0-9-]/,""); if(19428>$1)m++;n++; } END { print m/n }'
