### ISSUE TITLE
Simple comments being parsed as markdown.. possibly incorrectly?

### ISSUE THREAD

**Issue by qbit** [jcs/lobsters#217]
Comments containing "K." are changed in preview and when posting to "a.".

**Comment by brycied00d** [comment]
Can confirm. Any comment, and presumably any other field that is passed through the markdown interpreter, that consists solely of "<letter>." is interpreted as a list, and turned into:
```
    <div class="comment_text">
        <ol type="a">
<li></li>
</ol>


    </div>
```

**Comment by jcs** [comment]
RDiscount/discount does that.  I just checked in Mou and it does it as well, but I'm not sure what it uses for the backend.

````
irb(main):007:0> RDiscount.new("K.").to_html
=> "<ol type=\"a\">\n<li></li>\n</ol>\n\n"
````

`:strict` helps but I don't know what it breaks.

````
irb(main):008:0> RDiscount.new("K.", :strict).to_html
=> "<p>K.</p>\n"
````

**Comment by brycied00d** [comment]
Formatting-wise, it looks like it breaks the use of ^ and _ within words.

If you read sourcecode easier, it's the 4 instances of "strict" on https://github.com/Orc/discount/blob/master/generate.c
