### ISSUE TITLE
Order RSS feeds by most recent pubDate

### ISSUE THREAD

**Issue by bconway** [jcs/lobsters#220]
Historically, RSS feeds were ordered chronologically. More importantly, a number of RSS reader services are short-sighted (buggy) and don't parse the entire RSS every time, but rather stop when they hit an item they've seen before, assuming they've found everything new. In that scenario, an unchanging top item with a lot of following items that do change don't get picked up by said services until much later when they do a full parse.

I see this a lot more with a personalized RSS feed, which doesn't have nearly as much churn as the main site/RSS.

**Comment by jcs** [comment]
But that would break the ordering for RSS readers that aren't storing everything but just showing the current view and refreshing every so often.

**Comment by bconway** [comment]
That's a thing?

Okay, closed I guess.

**Comment by bconway** [comment]
FYI- I ended up rolling this myself using hottest.json?token=X, so please
don't take away the use of token there. ;) I've only seen it publicized in
the context of personalized RSS, so I figured I'd mention it.

Brian Conway
