### ISSUE TITLE
Comment folding is not available for guests

### ISSUE THREAD

**Issue by daGrevis** [jcs/lobsters#223]
Sometimes I like to read Lobste.rs on my phone (on which I'm not logged in), but I can't fold comments there. Arguably the comment folding feature shines the most on phones because of their small screen size.

What's the point of not showing fold button for guests?

If I understand the code correctly, it can be fixed by removing [this check](https://github.com/jcs/lobsters/commit/4ddfaa89647c407ab5a043a7178170c5d97f4b20#diff-ab7dbdfb2fa4302d21356a0e615620e3R66).

**Comment by jcs** [comment]
None of the Javascript assets are served to logged-out users, for faster loading.

**Comment by daGrevis** [comment]
Ahh, I see. That sucks. :(

I guess the best option for now will be to log in.

**Comment by tannakartikey** [comment]
@jcs how to serve assets for all if we wish to. I couldn't find anything in README or in any other issue.

**Comment by pushcx** [comment]
@tannakartikey Please ask random codebase support questions in [the chat room](https://lobste.rs/chat) rather than posting to unrelated closed issues. This is a small change I can point you directly to.

**Comment by tannakartikey** [comment]
Oh sorry I asked it wrong.
What I meant that the behaviour is not documented anywhere. Can I send a PR describing this behaviour in README?
