### ISSUE TITLE
more rss feeds

### ISSUE THREAD

**Issue by jaesivsm** [jcs/lobsters#225]
This is a feature request.

I think lobste.rs could benefit of two more feeds.

One pretty similar to the one already provided by lobsters. The only difference would be that, instead of listing links to the external article, it would list links to the corresponding entry in lobsters. I'd suggest to make that the main feed (presented before the other one in the meta's) as it would encourage feeds users to get more into the comments and participate.

The other one may be a bit more work. For each entry in lobsters, a feed referencing the comments order by creation date would be also nice to have.

**Comment by jcs** [comment]
The RSS feed there already has `<comments>` entries that point back to the lobste.rs page for each story.

For comments, there is a JSON feed for them at the story URL plus "`.json`".

https://lobste.rs/s/4tdmpz/os_x_10_11_el_capitan_the_ars_technica_review.json
