### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by neophiliac** [jcs/lobsters#228]
I have Lobsters running in vagrant (Ubuntu 14.04), and I have followed the instructions and made no other changes. Running the tests I get [13 errors.](https://gist.github.com/neophiliac/74725b779df62b953a14)

Is this expected?

**Comment by jcs** [comment]
Yes, that test suite is quite bad and never updated.

**Comment by daGrevis** [comment]
Why aren't tests removed from the repo? There is no point in failing tests.

**Comment by jcs** [comment]
For the same reason they fail: nobody is paying attention to them.
