### ISSUE TITLE
Google marking lobsters mails as spam

### ISSUE THREAD

**Issue by nathan-hoad** [jcs/lobsters#229]
I get lobsters posts sent to me via email, and I've noticed quite a few coming up in spam recently (at least since a month ago), with the reason for them being "It's in violation of Google's recommended email sender guidelines.", referencing here as an explanation: https://support.google.com/mail/answer/81126?hl=en-GB&authuser=1#authentication

I couldn't find any other bug reports about this, so I thought you may not be aware of it.

**Comment by jcs** [comment]
\*shrug\*
