### ISSUE TITLE
Include comments from stories you submit under "Your Threads"

### ISSUE THREAD

**Issue by stig** [jcs/lobsters#231]
I tend to think of myself as being part of a thread if I submit a story, even if I haven’t commented on it yet. 
[I raised this as a topic](https://lobste.rs/s/lhj6al/should_stories_you_submit_be_included_in_your_threads) and I judge people to be generally in favour; at least nobody spoke up against the idea!

**Comment by pushcx** [comment]
I missed the topic, but would also like this.
