### ISSUE TITLE
New tag suggestions

### ISSUE THREAD

**Issue by fitzgen** [jcs/lobsters#234]
Unsure where to suggest new tags, if this is an incorrect location then I'd appreciate a pointer to the right location.

Suggestions (and examples from my own submissions where I would have liked to use the suggested tag):

* Profiling - Things related to cpu/memory profiling tools, telemetry, implementation, and techniques. Use cases, papers on novel methods of profiling, etc...

  * https://lobste.rs/s/0ral1u/coz_finding_code_that_counts_with_causal_profiling

  * https://lobste.rs/s/lamfri/lag_drag_void_and_use_-_heap_profiling_and_space_efficient_compilation_revisited

* Concurrency/Parallelism - Articles relating to concurrent and/or parallel programming and programming paradigms. Shared memory, message passing, map/reduce, etc...

  * https://lobste.rs/s/0ral1u/coz_finding_code_that_counts_with_causal_profiling

  * https://lobste.rs/s/9r57l4/organn_-_a_simple_drawbar_organ_synth_in_rust

  * https://lobste.rs/s/8tgsml/mozpromise_a_better_tool_for_asynchronous_c

  * https://lobste.rs/s/fvvk8s/must_be_this_tall_to_write_multi-threaded_code

* Garbage Collection / Memory Management - Submissions relating to garbage collection / reference counting algorithms, implementation, performance tuning, etc...

  * https://lobste.rs/s/uwj7d1/erlang_garbage_collection_details_and_why_it_matters

  * https://lobste.rs/s/lamfri/lag_drag_void_and_use_-_heap_profiling_and_space_efficient_compilation_revisited

  * https://lobste.rs/s/c6gafh/compacting_garbage_collection_in_spidermonkey

**Comment by jcs** [comment]
New tags need to be submitted as /t/meta posts so users can discuss/vote on them.

**Comment by fitzgen** [comment]
One for each tag, or one post for all of them?

**Comment by jcs** [comment]
Probably one post, maybe make a root comment for each new tag for people to discuss them.
