### ISSUE TITLE
Filtering domains

### ISSUE THREAD

**Issue by untitaker** [jcs/lobsters#241]
See https://lobste.rs/s/uzyuoy/is_google_violating_their_own_hpkp_rfc_or_am_i_missing_something_obvious/comments/0ekxno#c_0ekxno

>Can I suggest a twitter tag as a medium (this could also be applied to webpages that are just posting a bunch of twitter entries), or something similar that will make it easy to filter out these?

A tag would be one way to solve this, but I think it'd be nice to be able to filter specific domains out of the personal frontpage. Such as `twitter.com`.

**Comment by m50d** [comment]
As I said on the thread, I think it's more appropriate as a medium/format tag, since domains which are not twitter.com often post collections of tweets.

**Comment by jcs** [comment]
I don't think blanket bans on certain domains is a good idea.  There can be crap at legitimate domains and valuable info at typically crappy domains.  I think each story should be voted upon based on its content.

**Comment by untitaker** [comment]
@jcs I could reuse your argument to make a case against tag filtering.

**Comment by Summertime** [comment]
It'd be really great to be able to filter such since I really don't want to ever see any content from people who use stuff like ["you should be gang raped"](https://lobste.rs/s/mxb8wb/debian_12_is_better_than_windows_10) in their writings.

Its not off-topic, its not a broken link, its not already posted, its not spam. None of the downvoting reasons apply.

**Comment by untitaker** [comment]
yeah, this issue has become worse over the years. I am not going to evaluate the same author's writing for the Nth time and arrive at a different conclusion. And unfortunately there are a few posters particularly on lobste.rs that drown out other content for me and ruin the experience.

**Comment by pushcx** [comment]
@Summertime Message a [current moderator](https://lobste.rs/moderators) when you see stuff like that, please. I've handled this one.
