### ISSUE TITLE
pluggable search backend

### ISSUE THREAD

**Issue by sandys** [jcs/lobsters#243]
hi,
I'm really looking forward to running lobste.rs internally for a community project in India. We plan to host on AWS, and use RDS for the database and some hosted solution (most likely elasticsearch based) for powering search.

unfortunately, there are not too many hosted alternatives for sphinx. 

would it be possible for you to have a switchable search backend - elasticsearch and sphinx would be the two that you could have (and the rest could be built by the community ). that would be really awesome!

**Comment by jcs** [comment]
I'm not going to write it, but there's nothing stopping you from doing so.
