### ISSUE TITLE
Give more invite info

### ISSUE THREAD

**Issue by pushcx** [jcs/lobsters#244]
I'd like to add more explicit information on how to get an invitation to the about and chat pages, as I've met a number of people who've glanced off the site due to not having clear next steps. This is an attempt to make the chat room's general sentiment more explicit, so I'd appreciate if folks would chime in - I'm linking this from the chat room and a meta thread.

(The about and chat pages are gitignored or I'd PR.)

On /about, after "promote exclusivity", I'd add:

> The best way to get an account is to talk to someone you recognize from the site, but you can also get one from the [chat room](/chat).

And on /chat, I'd add two things. To the end of the first paragraph:

> The chat room isn't busy enough that there's always someone talking, so don't be surprised if you try to start a conversation and no one responds. Leave it open and you'll see activity, though we're most active in US work hours.

And I'd replace "Asking users in the channel for invitations to Lobsters is not acceptable." with

> Interesting people are always welcome on Lobsters, but spamming the chat room for invites is not acceptable. If you are the author or otherwise involved with a story on the site, ask and someone will invite you. Alternately, offer some good links or thoughts on a story and someone will likely invite you so can post them.

**Comment by NattyNarwhal** [comment]
"Interesting people" to me implies really special people, which people might not perceive themselves as. I think something else might fit better; people interested in contributing, maybe?

**Comment by pushcx** [comment]
I think that is an excellent criticism. Maybe just "New contributors are..."

**Comment by jcs** [comment]
Ok I added text in various places.
