### ISSUE TITLE
documentation - lobsters installation dependencies

### ISSUE THREAD

**Issue by Hovden** [jcs/lobsters#248]
Consider adding to the documentation a list of likely dependencies for running Lobsters. When setting up lobsters I found many dependencies were required to install—slowed me down.

Here is a partial list that was required for me (fresh Ubuntu install) and I think would be useful to other people setting up lobsters.
apt-get: mysql-server, nodjs, libxml2-dev, libxslt-dev
gem: nokogiri
*note that installing mysql-server required that I first purge the mysql-core build on my machine.

Cheers!
-Rob

**Comment by jcs** [comment]
Nokogiri is in the Gemfile, did you run `bundle` to install all of the gems?

**Comment by Hovden** [comment]
Yeah. I had to go back and get nokogiri after rake was not working. Install may have failed because of missing applications later grabbed with apt-get?

Now I'm working on setting up the requirements for mail invitations to work (presumably requires setting up a local SMTP server). Trying to document my steps since it is a fresh install. Code is clean, organized — just need to learn what's where.

**Comment by vaMuchenje** [comment]
during installation, I  get a scary error:

`/var/lib/gems/2.2.0/gems/activesupport-4.1.12/lib/active_support/lazy_load_hooks.rb:27:in `each'                                                                                  
/var/lib/gems/2.2.0/gems/activesupport-4.1.12/lib/active_support/lazy_load_hooks.rb:27:in `on_load'                                                                               
/var/lib/gems/2.2.0/gems/activerecord-4.1.12/lib/active_record/railtie.rb:116:in `block in <class:Railtie>'                                                                       
/var/lib/gems/2.2.0/gems/railties-4.1.12/lib/rails/initializable.rb:30:in `instance_exec'                                                                                         
/var/lib/gems/2.2.0/gems/railties-4.1.12/lib/rails/initializable.rb:30:in `run'                                                                                                   
/var/lib/gems/2.2.0/gems/railties-4.1.12/lib/rails/initializable.rb:55:in `block in run_initializers'                                                                             
/var/lib/gems/2.2.0/gems/railties-4.1.12/lib/rails/initializable.rb:54:in `run_initializers'                                                                                      
/var/lib/gems/2.2.0/gems/railties-4.1.12/lib/rails/application.rb:300:in `initialize!'                                                                                            
/var/lib/gems/2.2.0/gems/railties-4.1.12/lib/rails/railtie.rb:194:in `public_send'                                                                                                
/var/lib/gems/2.2.0/gems/railties-4.1.12/lib/rails/railtie.rb:194:in `method_missing'                                                                                             
/home/codio/workspace/lob/config/environment.rb:5:in `<top (required)>'                                                                                                           
/var/lib/gems/2.2.0/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:247:in `require'                                                                                 
/var/lib/gems/2.2.0/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:247:in `block in require'                                                                        
/var/lib/gems/2.2.0/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:232:in `load_dependency'                                                                         
/var/lib/gems/2.2.0/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:247:in `require'                                                                                 
/var/lib/gems/2.2.0/gems/railties-4.1.12/lib/rails/application.rb:276:in `require_environment!'                                                                                   
/var/lib/gems/2.2.0/gems/railties-4.1.12/lib/rails/application.rb:405:in `block in run_tasks_blocks'                                                                              
Psych::SyntaxError: (<unknown>): did not find expected key while parsing a block mapping at line 1 column 1                                                                       
/var/lib/gems/2.2.0/gems/railties-4.1.12/lib/rails/application/configuration.rb:99:in `database_configuration'                                                                    
/var/lib/gems/2.2.0/gems/activerecord-4.1.12/lib/active_record/railtie.rb:126:in `block (2 levels) in <class:Railtie>'                                                            
/var/lib/gems/2.2.0/gems/activesupport-4.1.12/lib/active_support/lazy_load_hooks.rb:38:in `instance_eval'                                                                         
/var/lib/gems/2.2.0/gems/activesupport-4.1.12/lib/active_support/lazy_load_hooks.rb:38:in `execute_hook'                                                                          
/var/lib/gems/2.2.0/gems/activesupport-4.1.12/lib/active_support/lazy_load_hooks.rb:28:in `block in on_load'                                                                      
/var/lib/gems/2.2.0/gems/activesupport-4.1.12/lib/active_support/lazy_load_hooks.rb:27:in `each'                                                                                  
/var/lib/gems/2.2.0/gems/activesupport-4.1.12/lib/active_support/lazy_load_hooks.rb:27:in `on_load'                                                                               
/var/lib/gems/2.2.0/gems/activerecord-4.1.12/lib/active_record/railtie.rb:116:in `block in <class:Railtie>'                                                                       
/var/lib/gems/2.2.0/gems/railties-4.1.12/lib/rails/initializable.rb:30:in `instance_exec'                                                                                         
/var/lib/gems/2.2.0/gems/railties-4.1.12/lib/rails/initializable.rb:30:in `run'                                                                                                   
/var/lib/gems/2.2.0/gems/railties-4.1.12/lib/rails/initializable.rb:55:in `block in run_initializers'                                                                             
/var/lib/gems/2.2.0/gems/railties-4.1.12/lib/rails/initializable.rb:54:in `run_initializers'                                                                                      
/var/lib/gems/2.2.0/gems/railties-4.1.12/lib/rails/application.rb:300:in `initialize!'                                                                                            
/var/lib/gems/2.2.0/gems/railties-4.1.12/lib/rails/railtie.rb:194:in `public_send'                                                                                                
/var/lib/gems/2.2.0/gems/railties-4.1.12/lib/rails/railtie.rb:194:in `method_missing'                                                                                             
/home/codio/workspace/lob/config/environment.rb:5:in `<top (required)>'                                                                                                           
/var/lib/gems/2.2.0/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:247:in `require'                                                                                 
/var/lib/gems/2.2.0/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:247:in `block in require'                                                                        
/var/lib/gems/2.2.0/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:232:in `load_dependency'                                                                         
/var/lib/gems/2.2.0/gems/activesupport-4.1.12/lib/active_support/dependencies.rb:247:in `require'                                                                                 
/var/lib/gems/2.2.0/gems/railties-4.1.12/lib/rails/application.rb:276:in `require_environment!'                                                                                   
/var/lib/gems/2.2.0/gems/railties-4.1.12/lib/rails/application.rb:405:in `block in run_tasks_blocks'                                                                              
Tasks: TOP => db:schema:load => environment                                                                                                                                       
(See full trace by running task with --trace)`
