### ISSUE TITLE
The phrase "or request one in chat" is misleading

### ISSUE THREAD

**Issue by reezer** [jcs/lobsters#249]
On the about page there is a sentence:
>  The most efficient way to receive an invitation is to talk to someone you recognize from the site or request one in chat.

while on the chat page itself it says:
> spamming chat for invites is not acceptable

Now the term spamming can mean a lot of things and in the context of chat is frequently used to mean "repeated messaging" (and not unwanted advertisement, etc.).

While I am new to the community it seems that that "request one in chat" isn't really what one is supposed to do. Maybe this could be cleared up a bit by stating that after with good contributions one might get an invite in chat or something along these lines.

**Comment by jcs** [comment]
I blame @pushcx for this.  (See #244)

**Comment by pushcx** [comment]
I blame everyone else I asked for help who did not catch this typo. Big typo.
