### ISSUE TITLE
Tags field is checking for matches in description

### ISSUE THREAD

**Issue by pushcx** [jcs/lobsters#251]
Inverse of #247.

I sttarted typing `pro` which is what I have to type to get `programming` rather than `practices`. It never appeared, because all the language-specific tags that come before `p` include the word "programming" in their descriptions and were sorted above it.

Please sort tag matches before description matches.

**Comment by pushcx** [comment]
...and `sof` completes to `programming` before `software`, and `we` complets to `browsers` before `web`. Madness!

**Comment by jcs** [comment]
This was done on purpose to slow your submission rate down.
