### ISSUE TITLE
Invitations in early stage of site need to be emphasised.

### ISSUE THREAD

**Issue by mozboz** [jcs/lobsters#254]
This is a bit vague, I haven't gone into the code to see how this works yet, but in the 'Early Stage' of the site (say when there are < 100 users) I think there needs to be emphasis on existing users seeing new Invitiation Requests and being prompted to invite new members.

I'm not clear right now on who/when the Invitation Queue link in the footer is visible, but it seems to be hidden or not available to some users.

In 'Early Stage' I think it should be visible to all members all the time and perhaps even emphasised - e.g. visible in the header, or invitation requests firing a message to all users to emphasise that approving Invitation Requests is a community activity.

**Comment by jcs** [comment]
From README:
> While you are free to fork this code and modify it (according to the license) to run your own link aggregation website, this source code repository and bug tracker are only for the site operating at lobste.rs. Please do not use the bug tracker for support related to operating your own site unless you are contributing code that will also benefit lobste.rs.
