### ISSUE TITLE
Strike-through text doesn't seem to work. 

### ISSUE THREAD

**Issue by michaelochurch** [jcs/lobsters#257]
This morning, I submitted a comment using strike-through formatting, like so: ```~~hello~~``` and, instead of converting to strike-through (e.g. ~~hello~~), it left the tildes and the struck-through text in plain format.

**Comment by jcs** [comment]
RDiscount disables strikethrough when strict is on, which has to be enabled to avoid doing dumb things (see cbf14021ac).
