### ISSUE TITLE
"Receive List E-mails" does not work

### ISSUE THREAD

**Issue by tomjaguarpaw** [jcs/lobsters#258]
I just installed lobsters to create my own forum.  Everything I have checked is working fine except the "Receive List E-mails" setting.  Regardless of what I set it to I do not receive emails of new posts and stories.  The other email settings (Comment Reply Notification Settings, for example) seems to be fine.

Is there something special I should be configuring?

**Comment by jcs** [comment]
You need to run `script/mail_new_activity` from cron (probably every 5 minutes).
