### ISSUE TITLE
Build an oauth provider ?

### ISSUE THREAD

**Issue by sandys** [jcs/lobsters#260]
I think its a good idea to build an oauth2 provider inside lobsters (maybe using https://github.com/doorkeeper-gem/doorkeeper/wiki/api-endpoint-descriptions-and-examples). 

Because of the way that invites+audits work in lobsters, it becomes a brilliant trust source. Unfortunately, it cannot be leveraged outside of lobsters.

**Comment by jcs** [comment]
Sorry but I don't want this in Lobsters.
