### ISSUE TITLE
Saving stories (and maybe comments)

### ISSUE THREAD

**Issue by spinda** [jcs/lobsters#264]
Sometimes I see stories or comments on Lobste.rs that are good enough to save for later. Could a "save" link be implemented with the same sort of infrastructure as "hide"?

(I'd be willing to write a patch for this.)

**Comment by jcs** [comment]
https://lobste.rs/upvoted is not good enough?

**Comment by spinda** [comment]
Well, the set of things I upvote is larger than the set of things I'd want to save. But I guess that works. Is that page linked to from anywhere else in the UI?

**Comment by jcs** [comment]
I don't think so, there are quite a few pages that aren't linked to from anywhere.  There are a lot of links on the site in general and it's difficult to add more without adding clutter.
