### ISSUE TITLE
Check for recent submission when submission URL field loses focus

### ISSUE THREAD

**Issue by colindean** [jcs/lobsters#266]
A few times now, I've started to a submit a story, only to be told after filling out the form that it's already been submitted. It'd be a time saver to have immediate feedback if a URL has been submitted recently. I would imagine that the URL could checked as soon as the URL input loses focus.

**Comment by jcs** [comment]
Ironically, this has also already been submitted.  #149

**Comment by colindean** [comment]
I can't win!
