### ISSUE TITLE
User tree that excludes never-active users

### ISSUE THREAD

**Issue by anadrome** [jcs/lobsters#270]
Feature request.

Now that the [user tree](https://lobste.rs/u) has grown to 5000+ users, it's a bit unwieldy. One way it could be a little more useful (at least to me) is if there were an option to show a version of the tree that excluded never-active users, i.e. those who signed up but have never posted a comment or submitted a story.

**Comment by crertel** [comment]
To be clear, desired behavior would just be to omit users who both:

* Have no sumbmitted stories
* Have no comments

This is true, yes?

**Comment by anadrome** [comment]
Yeah, that's what I had in mind.

One extra question would be what to do about users who have no submitted stories and no comments, *but* have invited someone who does. To keep the tree as a tree, they would have to be kept as a placeholder interior node (maybe grayed out).

**Comment by crertel** [comment]
Hah, maybe just a flat list of users, sorted by <criteria, and have a "show heritage" button next to their name that expands to who invited them? And then the tree view can be something different?
