### ISSUE TITLE
Some e-mails with newly submitted stories have "=?UTF-8?Q?" prefix

### ISSUE THREAD

**Issue by RobustLocust** [jcs/lobsters#271]
Just got an e-mail titled _"=?UTF-8?Q?What are you working on this week? [ask]?="_. My uneducated guess is that the problem lies [here](https://github.com/jcs/lobsters/blob/master/script/mail_new_activity#L15) but I'm Ruby illiterate and have no idea what is wrong.

**Comment by jcs** [comment]
upgrade your e-mail client?

**Comment by RobustLocust** [comment]
It's a Fastmail web client :)

**Comment by RobustLocust** [comment]
Correct me if I'm wrong but [RFC2047](http://tools.ietf.org/html/rfc2047) explicitly forbids using '?' and space characters in encoded subject text (encoded-text). Question mark should be converted to two digit uppercase hex representation prepended with '=' sign ("=3F") and spaces should be converted to '_'.

**Comment by jcs** [comment]
https://en.wikipedia.org/wiki/MIME#Encoded-Word

**Comment by jcs** [comment]
Strangely the mail gem doesn't seem to care about question marks (the default QP encoding in Ruby doesn't encode them) but it does replace spaces with underscores, which I'm doing now.

https://github.com/mikel/mail/blob/master/lib/mail/encodings.rb#L221
