### ISSUE TITLE
emoji in URLs should be converted to the IDN punycode

### ISSUE THREAD

**Issue by NattyNarwhal** [jcs/lobsters#274]
URLs with Emoji inside of them (you can see some on [vhf's profile](https://lobste.rs/u/vhf)) are not converted to punycode. This throws off Edge 13 and Firefox at least.

**Comment by jcs** [comment]
They work fine for me in Firefox (hovering shows xn--13h).

Either way, I don't think this conversion should be done server-side, it should just return whatever the user types in.  If the user is entering in something that is not supported by other browsers, the user should fix it.
