### ISSUE TITLE
can no longer access lobste.rs with Browser on Android 4.2.2

### ISSUE THREAD

**Issue by cnst** [jcs/lobsters#279]
Starting from today, it seems like it is not longer possible to access lobsters on one of my 3-year-old phones, which is running Browser on Android 4.2.2.

I'm receiving a message: "Couldn't establish a secure connection".

Other websites, like reddit and hacker news, continue to work normally.

**Comment by jcs** [comment]
¯\\\_(ツ)\_/¯

https://www.ssllabs.com/ssltest/analyze.html?d=lobste.rs&s=207.158.15.114&latest

**Comment by cnst** [comment]
Well, it wasn't working all day yesterday, even though ssllabs did seem to indicate even yesterday that it is supposed to work, but today it's all back to business.  No change on your side?  T-Mo US is the network, FWIIW.

**Comment by jcs** [comment]
no change on my side
