### ISSUE TITLE
fix remaining markdown issues

### ISSUE THREAD

**Issue by jcs** [jcs/lobsters#288]
- tildes for strikethrough don't work, because we have to pass `:strict` (see cbf14021ac06).
- `@username` expansion doesn't work, because of security issues (see 0f498d3ee3).

**Comment by zgrep** [comment]
It would be nice to also have the ability to do superscript (currently disabled by `:strict`), or at least to enable `:footnotes`.

**Comment by kivikakk** [comment]
I'm currently working on integrating extensions to the [CommonMark](http://commonmark.org/) spec (which includes strikethroughs) into the Ruby CommonMarker library at https://github.com/gjtorikian/commonmarker/pull/28.

Would you be interested in a PR to lobste.rs that switched to CommonMarker? `@username` expansion should be pretty easy to safely add after that which a walk through the cmark AST.

**Comment by kevinburke** [comment]
Not sure if I should open a ticket. I posted text today that looked like this:

```
I'm working on https://github.com/kevinburke/ansible-go, a project that ...
```

This automatically created a link but the HREF included the comma, so the underlined+linked text was `https://github.com/kevinburke/ansible-go,`

This is probably right by the spec but not right by design - maybe if a URL end matches `, ` the comma should be omitted.

**Comment by daGrevis** [comment]
What about links with actual comma in them?

http://www.wolframalpha.com/input/?i=area+of+japan,+germany

**Comment by kivikakk** [comment]
The usual solution is to include all but trailing punctuation, optionally including trailing punctuation if they're of a matching balanced pair of parentheses (eg for Wikipedia links).

**Comment by jcs** [comment]
@kivikakk if you want to switch this to use CommonMarker and fix the `@username` expansion, please feel free.

**Comment by kivikakk** [comment]
@jcs :tada: #354
