### ISSUE TITLE
 warning: already initialized constant Rake

### ISSUE THREAD

**Issue by modInfo** [jcs/lobsters#292]
lobsters@lobsters:~/lobsters$ rake db:schema:load
/home/lobsters/lobsters/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake.rb:24: warning: already initialized constant Rake::VERSION
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake.rb:24: warning: previous definition of VERSION was here
/home/lobsters/lobsters/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/version.rb:3: warning: already initialized constant Rake::Version::MAJOR
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/version.rb:3: warning: previous definition of MAJOR was here
/home/lobsters/lobsters/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/version.rb:3: warning: already initialized constant Rake::Version::MINOR
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/version.rb:3: warning: previous definition of MINOR was here
/home/lobsters/lobsters/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/version.rb:3: warning: already initialized constant Rake::Version::BUILD
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/version.rb:3: warning: previous definition of BUILD was here
/home/lobsters/lobsters/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/version.rb:3: warning: already initialized constant Rake::Version::OTHER
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/version.rb:3: warning: previous definition of OTHER was here
/home/lobsters/lobsters/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/version.rb:5: warning: already initialized constant Rake::Version::NUMBERS
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/version.rb:5: warning: previous definition of NUMBERS was here
/home/lobsters/lobsters/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake.rb:31: warning: already initialized constant RAKEVERSION
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake.rb:31: warning: previous definition of RAKEVERSION was here
WARNING: Possible conflict with Rake extension: String#ext already exists
WARNING: Possible conflict with Rake extension: String#pathmap already exists
/home/lobsters/lobsters/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/early_time.rb:20: warning: already initialized constant Rake::EARLY
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/early_time.rb:20: warning: previous definition of EARLY was here
/home/lobsters/lobsters/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/late_time.rb:16: warning: already initialized constant Rake::LATE
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/late_time.rb:16: warning: previous definition of LATE was here
/home/lobsters/lobsters/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/alt_system.rb:34: warning: already initialized constant Rake::AltSystem::WINDOWS
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/alt_system.rb:34: warning: previous definition of WINDOWS was here
/home/lobsters/lobsters/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/linked_list.rb:100: warning: already initialized constant Rake::LinkedList::EMPTY
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/linked_list.rb:100: warning: previous definition of EMPTY was here
/home/lobsters/lobsters/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/scope.rb:40: warning: already initialized constant Rake::Scope::EMPTY
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/scope.rb:40: warning: previous definition of EMPTY was here
/home/lobsters/lobsters/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/file_utils.rb:9: warning: already initialized constant FileUtils::RUBY
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/file_utils.rb:9: warning: previous definition of RUBY was here
/home/lobsters/lobsters/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/file_utils.rb:100: warning: already initialized constant FileUtils::LN_SUPPORTED
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/file_utils.rb:100: warning: previous definition of LN_SUPPORTED was here
/home/lobsters/lobsters/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/file_utils_ext.rb:16: warning: already initialized constant Rake::FileUtilsExt::DEFAULT
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/file_utils_ext.rb:16: warning: previous definition of DEFAULT was here
/home/lobsters/lobsters/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/file_list.rb:44: warning: already initialized constant Rake::FileList::ARRAY_METHODS
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/file_list.rb:44: warning: previous definition of ARRAY_METHODS was here
/home/lobsters/lobsters/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/file_list.rb:48: warning: already initialized constant Rake::FileList::MUST_DEFINE
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/file_list.rb:48: warning: previous definition of MUST_DEFINE was here
/home/lobsters/lobsters/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/file_list.rb:52: warning: already initialized constant Rake::FileList::MUST_NOT_DEFINE
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/file_list.rb:52: warning: previous definition of MUST_NOT_DEFINE was here
/home/lobsters/lobsters/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/file_list.rb:56: warning: already initialized constant Rake::FileList::SPECIAL_RETURN
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/file_list.rb:56: warning: previous definition of SPECIAL_RETURN was here
/home/lobsters/lobsters/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/file_list.rb:62: warning: already initialized constant Rake::FileList::DELEGATING_METHODS
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/file_list.rb:62: warning: previous definition of DELEGATING_METHODS was here
/home/lobsters/lobsters/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/file_list.rb:374: warning: already initialized constant Rake::FileList::DEFAULT_IGNORE_PATTERNS
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/file_list.rb:374: warning: previous definition of DEFAULT_IGNORE_PATTERNS was here
/home/lobsters/lobsters/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/file_list.rb:380: warning: already initialized constant Rake::FileList::DEFAULT_IGNORE_PROCS
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/file_list.rb:380: warning: previous definition of DEFAULT_IGNORE_PROCS was here
/home/lobsters/lobsters/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/promise.rb:11: warning: already initialized constant Rake::Promise::NOT_SET
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/promise.rb:11: warning: previous definition of NOT_SET was here
/home/lobsters/lobsters/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:13: warning: already initialized constant Rake::CommandLineOptionError
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:13: warning: previous definition of CommandLineOptionError was here
/home/lobsters/lobsters/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:38: warning: already initialized constant Rake::Application::DEFAULT_RAKEFILES
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:38: warning: previous definition of DEFAULT_RAKEFILES was here
/home/lobsters/lobsters/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:787: warning: already initialized constant Rake::Application::FIXNUM_MAX
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/application.rb:787: warning: previous definition of FIXNUM_MAX was here
/home/lobsters/lobsters/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/task_arguments.rb:97: warning: already initialized constant Rake::EMPTY_TASK_ARGS
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/task_arguments.rb:97: warning: previous definition of EMPTY_TASK_ARGS was here
/home/lobsters/lobsters/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/invocation_chain.rb:54: warning: already initialized constant Rake::InvocationChain::EMPTY
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/invocation_chain.rb:54: warning: previous definition of EMPTY was here
/home/lobsters/lobsters/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/backtrace.rb:3: warning: already initialized constant Rake::Backtrace::SYS_KEYS
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/backtrace.rb:3: warning: previous definition of SYS_KEYS was here
/home/lobsters/lobsters/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/backtrace.rb:4: warning: already initialized constant Rake::Backtrace::SYS_PATHS
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/backtrace.rb:4: warning: previous definition of SYS_PATHS was here
/home/lobsters/lobsters/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/backtrace.rb:7: warning: already initialized constant Rake::Backtrace::SUPPRESSED_PATHS
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/backtrace.rb:7: warning: previous definition of SUPPRESSED_PATHS was here
/home/lobsters/lobsters/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/backtrace.rb:11: warning: already initialized constant Rake::Backtrace::SUPPRESSED_PATHS_RE
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/backtrace.rb:11: warning: previous definition of SUPPRESSED_PATHS_RE was here
/home/lobsters/lobsters/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake/backtrace.rb:15: warning: already initialized constant Rake::Backtrace::SUPPRESS_PATTERN
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake/backtrace.rb:15: warning: previous definition of SUPPRESS_PATTERN was here
/home/lobsters/lobsters/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake.rb:78: warning: already initialized constant FileList
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake.rb:78: warning: previous definition of FileList was here
/home/lobsters/lobsters/vendor/bundle/ruby/2.1.0/gems/rake-10.4.2/lib/rake.rb:79: warning: already initialized constant RakeFileUtils
/var/lib/gems/2.1.0/gems/rake-10.4.2/lib/rake.rb:79: warning: previous definition of RakeFileUtils was here
rake aborted!
SystemStackError: stack level too deep

Tasks: TOP => db:schema:load => environment

**Comment by pushcx** [comment]
What fixed it for you?

I'm guessing you had a system install of 'rake' alongside the gem install, and ` bundle exec rake db:schema:load` worked?

**Comment by wellington1993** [comment]
Hi, I removed `require 'bootsnap/setup'` from `boot.rb` and worked for me.
