### ISSUE TITLE
wrong ordering of top-level comments considering the votes and age

### ISSUE THREAD

**Issue by cnst** [jcs/lobsters#296]
Over at https://lobste.rs/s/iyhczp/systemd_developer_asks_tmux_other / http://web.archive.org/save/https://lobste.rs/s/iyhczp/systemd_developer_asks_tmux_other , I find the ordering of the top-level comments a bit strange -- https://lobste.rs/c/kx5wri is 32 hours old has has 13 votes, appears higher than https://lobste.rs/c/h14sqr, which is 29 hours old and has 25 votes.

What's going on?  If two comments are at the same level, shouldn't the newer one with more votes be higher up than an older one with fewer votes?

**Comment by pushcx** [comment]
The code is more complicated than that - it also depends on the ratio of upvotes to downvotes, not just the net. See [`calculated_confidence`](https://github.com/jcs/lobsters/blob/master/app/models/comment.rb#L165-181), which fills in the `confidence` values that the `StoriesController` fetches via [`arrange_for_user`](https://github.com/jcs/lobsters/blob/master/app/models/comment.rb#L47).

**Comment by cnst** [comment]
That's kinda weird.  Why are these numbers not shown, BTW?  I thought posts marked "incorrect" are supposed to have itemised scores etc?

**Comment by pushcx** [comment]
Probably because "6" is more useful than "1.043868349324" as a comment score. Check the comment view partial to see when those downvotes are shown.
