### ISSUE TITLE
user profile shows threads that don't belong to the user

### ISSUE THREAD

**Issue by cnst** [jcs/lobsters#297]
I've recently noticed that https://lobste.rs/threads/cnst http://web.archive.org/web/20160530052125/https://lobste.rs/threads/cnst has a whole bunch of threads where I'm not even participating, e.g., where I've simply posted a story, and that apparently makes every single comment within the story appear within.

In the past, that was only the case if at least one of the comments was made by me, which made the whole thread appear, but now they appear regardless whether any child comment is mine.

Is that intentional?

**Comment by pushcx** [comment]
In [settings](https://lobste.rs/settings), uncheck the box labeled "Show in Your Threads" and save, it controls the behavior you describe.

**Comment by cnst** [comment]
Interesting; but why is it the default?

**Comment by pushcx** [comment]
I dunno, look at the commit/issue/PR that added it.
