### ISSUE TITLE
should be possible to keep history of inviting users / memos

### ISSUE THREAD

**Issue by cnst** [jcs/lobsters#304]
I think it should be possible to see a history of inviting new users (especially when you fill-in something in the memo line).

Potentially, this may involve having a table within your account of all the invitations (and memos) you've ever sent, and usernames of people who have accepted.

At the minimum, it should be possible to receive a Cc of the invite, such that the history of outgoing invitations could be maintained through your mail.

(Yet another option would be to simply make the invite links available within the settings page, and thus make it possible to send custom emails/IMs/whatnot for inviting new members.)

**Comment by jcs** [comment]
Just email the invite to yourself and you'll get the link to hand out.
