### ISSUE TITLE
Travis CI

### ISSUE THREAD

**Issue by padi** [jcs/lobsters#307]
It would definitely help if there's CI in place whenever someone is making a pull request and the test is run on under multiple rubies. There's a bit of setup involved. Eventually, you will have to do some stuff that requires authentication from your account but I can do pretty much everything else like setting up the config file and adding the code snippet to the README.

```
[![Build Status](https://secure.travis-ci.org/jcs/lobsters.png)](http://travis-ci.org/jcs/lobsters)
```

It should look something like this: [![Build Status](https://secure.travis-ci.org/adomokos/light-service.png)](http://travis-ci.org/adomokos/light-service)

**Comment by jcs** [comment]
No thanks
