### ISSUE TITLE
Posting empty comment adds another comment box on page

### ISSUE THREAD

**Issue by polveenomials** [jcs/lobsters#315]
Clicking the post button with an empty comment box produces another comment box.

![image](https://cloud.githubusercontent.com/assets/11962639/16908575/4c882982-4cff-11e6-9bab-e5384a673ff4.png)

**Comment by zg** [comment]
I'm seeing this too. I initially thought it was specifically a bug in Safari, but I also found out that it's reproducible in Chrome too.

Safari Version: 10.0 (12602.1.38.2)
Chrome Version: 51.0.2704.106 (64-bit)
Operating system: macOS Sierra 10.12 Beta (16A238m)

**Comment by kunalvishnoi** [comment]
😋
