### ISSUE TITLE
How to add tags when submit new story?

### ISSUE THREAD

**Issue by yusiwen** [jcs/lobsters#319]
Sorry to bother with bringing up a new issue to ask this dumb question, but after poking around for a bit, I really don't know how to add tags when submit new story. There is only a 'test' tag, I can't put my custom tags in the 'Tag' input box, because when submitted, Tag input box is cleared.

How to add tags, and where to manager them? Thanks.

**Comment by pushcx** [comment]
There is no web UI for adding tags. The site expects that the admin creates the tags they want and only adds them slowly over time. There is no free-form tag creation when adding a story.

In the Rails console, run `Tag.create(tag: "hello", description: "example tag", is_media: false)`.

**Comment by crertel** [comment]
The `is_media` flag is used for things like `video`, `audio`, etc. right @pushcx ?

**Comment by pushcx** [comment]
Yes. Tags also have a privileged flag, inactive flag, and hotness modifier.

**Comment by ckib16** [comment]
For future documentation / wiki:

Here are the tag attributes in schema.rb
```
# Tag attributes
# t.string  "tag",         limit: 25,  default: "",    null: false
# t.string  "description", limit: 100
# t.boolean "privileged",              default: false
# t.boolean "is_media",                default: false
# t.boolean "inactive",                default: false
# t.float   "hotness_mod", limit: 24,  default: 0.0
```

Here's a portion of a sample seed file with all of them:
```
Tag.create(tag: "test", description: "test tag")
puts "created tag: test"

Tag.create(tag: "privileged", description: "privileged tag", privileged: true)
puts "created tag: privileged"

Tag.create(tag: "media", description: "media tag", is_media: true)
puts "created tag: media"

Tag.create(tag: "positive hotness", description: "positive hotness tag", hotness_mod: 1)
puts "created tag: positive hotness"

Tag.create(tag: "negative hotness", description: "negative hotness tag", hotness_mod: -1)
puts "created tag: positive hotness"

Tag.create(tag: "inactive", description: "inactive tag", inactive: true)
puts "created tag: inactive"
```

And here's what they appear as in the app:
![image](https://cloud.githubusercontent.com/assets/2160186/22371350/bd299688-e464-11e6-9ab3-b46019ec545d.png)
