### ISSUE TITLE
[feature request] Email notifications: Full-text stories with images

### ISSUE THREAD

**Issue by DanielHeath** [jcs/lobsters#327]
It would be great to attach images inline where a story needs it.

For instance, [the maze article](https://lobste.rs/s/u3lqtn/algorithms_for_making_more_interesting) doesn’t work at all without the images. 

Is this something people want? PR welcome?

**Comment by jcs** [comment]
This is a lot more complicated than just adding images, since now mailing list messages need to be in HTML, but re-formatted to be an e-mail, etc.

**Comment by DanielHeath** [comment]
Ahh, I see - it's calling out to diffbot to get those. 

For another project, I've just inlined all the HTML directly into an email, stripping `iframe` and `object` tags (they break some clients) and rewriting `img` tags to use attachments, which worked pretty well.
