### ISSUE TITLE
How to activate SSL?

### ISSUE THREAD

**Issue by thomaslule** [jcs/lobsters#330]
Hey, sorry if this isn't the right place for this question. I told nginx to access the site through https but I don't know how to activate it in lobsters. I get this kind of error when I try to display a page in https:

    [2016-12-13 11:51:42] ERROR bad Request-Line `\x16\x03\x01\x01\x1C\x01\x00\x01\x18\x03\x031▒59yH▒I\x032▒▒▒▒\x12o▒\e▒)k▒\x14o8▒\x1F▒#▒\x0E▒\x00\x00▒▒0▒,▒(▒$▒\x14▒'.

When I access the site in http, it works fine.

**Comment by jcs** [comment]
this has nothing to do with lobsters

**Comment by thomaslule** [comment]
Could you please tell me where should I look? Nginx? Rails? I have 3 other webapps with similar nginx configuration and I had to tell them where my ssl keys were located, so I assumed lobsters would need it too.
