### ISSUE TITLE
Use archive.org instead of archive.is

### ISSUE THREAD

**Issue by picsi** [jcs/lobsters#331]
Archive.is is a company without a business model, while archive.org is a non-profit with millions of donators. Needless to say, the Internet Archive will stick around for much much longer, and is thus a more reliable place to store caches.

**Comment by volth** [comment]
Could you change ```archive.is``` to ```archive.today```?
The reason is as the archive caches everything some of its domains are blocked in some countries.
```archive.today``` redirects to a working domain based on the visitor's geolocation while having very little chances to be blocked as it does not host cached pages.

**Comment by volth** [comment]
... and if the url contains ```#``` you should replace it with ```%23```: ```http://archive.is/https://twitter.com/%23!/jhapadon```
