### ISSUE TITLE
Add link to hide post in post+comment emails? 

### ISSUE THREAD

**Issue by stig** [jcs/lobsters#332]
I like to get posts + comments by mail, but I'd love to have a way to opt-out of more comments for certain threads. I envisage a "Hide" link in the email (similar to the "Vote" link) that would hide the articles (which I assume also stops any further comments from being mailed to me).

I would like this link to be added to the comment emails as well as the initial post emails, as often I don't know that the comments are uninteresting until the discussion has already derailed. If I've already deleted the original story mail, it's handy to have that link in the comment mail.

This feels a bit like #78, but from the "other side" so to speak.

**Comment by pushcx** [comment]
Maybe the best way to support this (with some nice knock-on benefits) would be to set email headers and the let client do it:

 * `Message-Id`: with a unique value, maybe `<reply-short_id@example.com>`.
 * `In-Reply-To`: parent's `Message-Id`
 * `References`: all parents' ids, oldest first

Email clients will pick up the thread, grouping responses (the extra benefit), and can easily mute the thread.

**Comment by jcs** [comment]
@pushcx: it has been that way since the initial feature was implemented, is threading not working for you?

https://github.com/jcs/lobsters/blob/master/script/mail_new_activity#L189


![mail](https://cloud.githubusercontent.com/assets/9888/21438593/7bb1f672-c84f-11e6-851a-1629a26c1980.png)

**Comment by stig** [comment]
@pushcx I'd rather not have the mails arrive though. Though I admit it's mostly because my current mail client [doesn't yet support muting messages](https://github.com/djcb/mu/issues/636)...

**Comment by pushcx** [comment]
@jcs That's the mailing list, I thought stig was asking about the [reply notification](https://github.com/jcs/lobsters/blob/master/app/mailers/email_reply.rb), which doesn't. Now that I reread I see he's not, but it still might be a nice little addition to those.
