### ISSUE TITLE
Leave in Google Analytics parameters, sometimes

### ISSUE THREAD

**Issue by listrophy** [jcs/lobsters#340]
Why does lobsters [strip out `utm_*` parameters](https://github.com/jcs/lobsters/blob/master/app/models/story.rb#L690-L698)?

The possible reasons I can think of are:

* Assume they were meant for elsewhere. For example, lobste.rs shouldn't provide URLs with `utm_medium=email` that someone copied from a newsletter they got. (I find this to be the most likely scenario, and pretty reasonable)
* Cleaner URLs.
* Disdain for deep analytics. There's too much tracking going on these days, so why propagate it?

Thoughts?

If it's the first thing, I suggest scrubbing `utm_*` parameters only if `utm_source !~ /lobste\.?rs/`

**Comment by jcs** [comment]
All 3 of those, yes.  I think it was initially added to make it easier to find similar URLs when submitting stories, and the canonical URL finding (from meta tag) will strip out these parameters anyway.
