### ISSUE TITLE
Feature idea: claim authorship

### ISSUE THREAD

**Issue by jonhoo** [jcs/lobsters#346]
Lobste.rs already allows you to claim "author" status of an article when posting it. However, every now and again, someone else will post an article that you've written. It would be useful to be able to claim authorship in those cases too. For example, I wrote the [Students' Guide to Raft](https://lobste.rs/s/uep8lg/students_guide_raft), but it was recently posted by someone else to the site. It'd be nice if there could still be a highlight of some sort if I comment on that article to indicate that I was the original author.

If we wanted to take it one step further, we could perhaps even give authors some fraction of the karma that the post generates. Might be a decent way of bootstrapping the karma system for new users...

**Comment by jcs** [comment]
#171

**Comment by jonhoo** [comment]
@jcs I don't think #171 addresses this. I am specifically talking about when *other* users share some *I* have written. I don't have a way of claiming ownership for the thing *they* posted.

**Comment by jcs** [comment]
@jonhoo It does, and I didn't see a way to properly claim ownership of other articles/domains, so I ended up implementing it as just a checkbox on the submission page for your own articles.

**Comment by jonhoo** [comment]
@jcs Maybe I'm just being incredibly dense here, but following the change in #171, how would I mark https://lobste.rs/stories/uep8lg as authored by me? It *seems* like #171 only lets me mark a story that *I* submit as authored by me?

**Comment by Hexstream** [comment]
> If we wanted to take it one step further, we could perhaps even give authors some fraction of the karma that the post generates. Might be a decent way of bootstrapping the karma system for new users...

I love that idea, since I create a lot of relevant content and would generally rather let others post what they think is interesting instead of "spamming" my own content. It would be nice if it was still possible to get karma this way.
