### ISSUE TITLE
[feature request] ability to add new tags while posting a link

### ISSUE THREAD

**Issue by Vertux** [jcs/lobsters#348]
It would be nice if admins and/or moderator (maybe users too) could add new tags on the fly while posting a link.

**Comment by jcs** [comment]
This goes against the way tags define the type of content users want on the site.

**Comment by Vertux** [comment]
I do not understand your argument, it would be comfort feature for admins/moderators. You have to define tags and maybe you have to add additional tags over the time, because there is a need for a more fine graded structure. It is not very comfortable to use the rails console for any modification.

**Comment by crertel** [comment]
Admin comfort is secondary to community responsiveness--if you look at how the Lobsters site is run, new tag suggestions and requests are the result of extensive discussion. Since it's a low-frequency activity, there doesn't need to be a feature like the one you've proposed.

**Comment by Vertux** [comment]
Well, that means you do not have any interest to make the software more comfortable and by association more interesting for other people who are not experienced programmers and people who maybe  want to run their website in a different way. I respect your opinion, but I am a little bit disappointed. That's the first open source project, I have seen, which is totally focus on one website/community. Thanks for your explanation.

**Comment by pushcx** [comment]
As a contributor the project, I would like to apologize that all the free code we published was not enough free code or perfectly suited to your needs. I respect your opinion, too.
