### ISSUE TITLE
Login username field is not an email address!

### ISSUE THREAD

**Issue by whbboyd** [jcs/lobsters#351]
Commit 7376958084b145285a543d3bc9c68f1fc98417d3 changed the username field in the login page to only accept email addresses; however, my username is not an email address, and I don't believe I have an email address associated with lobste.rs (and if I do, I don't know what it is). Thus, I cannot log in.

(The reset password page also should not require an email address; I'm not sure about the other fields changed as part of that commit.)

**Comment by jcs** [comment]
#350
