### ISSUE TITLE
Allow content and comments to be precached for offline viewing

### ISSUE THREAD

**Issue by wildlyinaccurate** [jcs/lobsters#360]
I use Lobsters a lot on my phone while I take the subway, and wish I could read the links and comments while I'm offline. Using [service workers](https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API/Using_Service_Workers) we could add functionality (perhaps behind an account setting) that pre-caches all of the links on the first page, as well as the comments for each link.

What do you think about this? I'd be happy to do the work and open a PR. I just wouldn't want to throw a load of code at you if you don't like the idea.

**Comment by jcs** [comment]
Sorry but I don't think that would be used by enough users to warrant all the extra baggage to support it.

**Comment by wildlyinaccurate** [comment]
No problem. Let me know if you change your mind -- I'd be happy to help out.
