### ISSUE TITLE
Apply “canonicalization” to user-submitted links as well

### ISSUE THREAD

**Issue by jnboehm** [jcs/lobsters#374]
This would solve, for example, linking to wikipedia articles from the mobile site, as they put the link to the normal page into the `canonical` tag.

It should probably apply the same canonicalization as the one for title links, would make #368 a bit more urgent.

**Comment by pushcx** [comment]
This would make it impossible to submit sites that have the most common case of bad canonical tag where the canonical tag points at the homepage. That would pass a 2xx status check.

**Comment by jcs** [comment]
I'm not sure what you mean by "user-submitted links", they are all user-submitted links.  Do you mean in comments or something?

**Comment by pushcx** [comment]
I'm pretty sure he means the URL entered by a user who clicks Submit without clicking "Fetch Title" or using the bookmarklet, which are the two current workflows where Lobsters replaces the URL with the one from the canonical tag.

**Comment by jnboehm** [comment]
Uh sorry, yes I meant the urls submitted in comments.  

I personally never noticed that the canonical URL is not always retrieved on link submission

**Comment by pushcx** [comment]
Wait, so if I wrote `[foo](https://mobile.bar.com/page)` in a comment and that page had a canonical tag, you'd want my comment rewritten to `[foo](https://foo.com/otherpage)`? That sounds like an unpleasant surprise

**Comment by jcs** [comment]
Yeah, I don't think that's a good idea.  Just from a technical perspective, comments are posted quickly and trying to fetch all URLs before accepting them would slow things down quite a lot.

**Comment by jnboehm** [comment]
> Wait, so if I wrote `[foo](https://mobile.bar.com/page)` in a comment and that page had a canonical tag, you'd want my comment rewritten to `[foo](https://foo.com/otherpage)`?

Yeah, I didn't notice that canonical tags can change the meaning of the page (I never knowingly encountered it so far).  My intention was changing e. g. `https://en.m.wikipedia.org/wiki/Immunity-aware_programming` to `https://en.wikipedia.org/wiki/Immunity-aware_programming`.
Probably does not make sense to implement that as long as semantically wrong canoncial tags are still prevalent.
