### ISSUE TITLE
Add downvote category for inappropriate/hostile comments

### ISSUE THREAD

**Issue by jonhoo** [jcs/lobsters#376]
Currently, the available downvote categories for comments [are](https://github.com/jcs/lobsters/blob/108baedb39206198e442a5bb0828c644862a79e0/app/models/vote.rb#L6):

 - Off-topic
 - Incorrect
 - Me-too
 - Troll
 - Spam

It is unclear from this list how comments that can be construed as inappropriate, hostile, or abusive should be tagged. As with all kinds of downvoting there's a fine line to walk here, but it doesn't feel right to tag such posts as "Troll" (which is probably the most related of the categories above). I'm not entirely sure what this new category should be called ("Abuse" may be too strong), but I do feel like one should be added.

**Comment by jcs** [comment]
I think troll is fine for that, but either way, this is something that would need to be discussed in a `meta`-tagged post on the site.

**Comment by jonhoo** [comment]
Posted at https://lobste.rs/s/wei3a9/downvote_category_for_inappropriate

**Comment by jonhoo** [comment]
Following on from https://lobste.rs/s/wei3a9/downvote_category_for_inappropriate#c_pryqvi, I think the current list is fine.

**Comment by jonhoo** [comment]
Re-opening following discussion in https://lobste.rs/s/wei3a9/downvote_category_for_inappropriate#c_2ztjbd.

**Comment by jonhoo** [comment]
I'm going to try and give a fair and (relatively) concise summary of the discussion thus far so people won't have to read through the 154 comments currently on the linked thread. I'll do this in the form of linked quotes, as that may also give additional context. I have tried to include relevant comments from both sides of this debate, but have probably failed to do so. My own, more compact, but also more subjective, summary is at the bottom of this post.

> Scorn, showing off, and put-downs shut people down fast, especially the newbies and minorities. Kindness is the fuel of a good community.
— [pushcx](https://lobste.rs/s/wei3a9/downvote_category_for_inappropriate#c_2ztjbd)

> I think uncharitable should be a new downvote flag. I’m okay with dissent, I’m okay with people being assholes, I’m even somewhat okay with outright negativity, as long as the comment is also charitable to the other viewpoint.
— [peter](https://lobste.rs/s/wei3a9/downvote_category_for_inappropriate#c_86eabt)

> Better to drop [such comments] to bottom of thread hidden by default with a plus or profile setting that can display them. That keeps them out of sight with votes but avoids total censorship where people can still read what was said.
— [nickpsecurity](https://lobste.rs/s/wei3a9/downvote_category_for_inappropriate#c_z6f6hc)

> I *appreciate* people being willing to voice unpopular opinions that can be taken as hostile. I don’t like a community of people who tiptoe around my statements, and aren’t willing to tell me that I’m saying something stupid when I say stupid things. [..] If there is a category that’s added, I’d want it to be specifically for deliberate distortions, misinterpretation, and blowing statements out of proportion. Possibly call it, “Bad faith”. But if that is added, I think it should be a superset of troll. If it’s added, troll should be removed.
— [orib](https://lobste.rs/s/wei3a9/downvote_category_for_inappropriate#c_74ydrb)

> That is to say, a comment is not written with the intent of discussing a genuinely held belief of the author, nor to expore new ideas, nor to discuss an important weakness in a previous comment. Instead, the comment may be made in order to derail discussion, to make people angry, or to belittle others, or to stroke the poster’s ego.
— [orib](https://lobste.rs/s/wei3a9/downvote_category_for_inappropriate#c_alpyqx)

> There is a pretty big difference between comments that contain heated and/or unpopular options and comments that are outright hurtful and abusive. I value a community that lets people express their (non-abusive/hostile/trollish) views without fear of a ban or harassment.
— [binarycleric](https://lobste.rs/s/wei3a9/downvote_category_for_inappropriate#c_5fx1yq)

> [W]e should have a way of discouraging comments that are solely inflammatory without carrying other value [..] I don’t want to see downvotes used as a way to signal disagreement, nor do I want them to be used to “punish” a particular user or otherwise label the user as bad. Downvotes to me are a way of signaling that a *particular* comment is unwanted, along with the reason why, nothing more, nothing less.
— jonhoo [1](https://lobste.rs/s/wei3a9/downvote_category_for_inappropriate#c_iyxbo2) [2](https://lobste.rs/s/wei3a9/downvote_category_for_inappropriate#c_hfapik)

> I think having an explicit downvote category for nonconstructive / hostile comments would benefit us. I think many of the points I’ve made about the exclusion of specific groups of people also apply in the context of being a welcoming community in general, and improving the general quality of discussion.
— [mcheely](https://lobste.rs/s/wei3a9/downvote_category_for_inappropriate#c_nrphdc)

> I think there is real value to having a conversation be civil, and *especially* so if it’s with someone I disagree with, and that’s what I’ve been suggesting here. That the *way* in which you put your argument into words matters, and that you should take care to make it precise and to-the-point. Otherwise it all reduces to petty shit-posting back and forth, which serves no-one and resolves no disagreements.
— [jonhoo](https://lobste.rs/s/wei3a9/downvote_category_for_inappropriate#c_mrzipz)

> I think “Troll” should be replaced with “Low-Effort”.
— [N64N64](https://lobste.rs/s/wei3a9/downvote_category_for_inappropriate#c_h7uvtt)

> Personally, I’m fine with “you’re wrong, here’s why”. I’m not fine with “you’re wrong, here’s why, fuck you, fuck off. “
— [hwayne](https://lobste.rs/s/wei3a9/downvote_category_for_inappropriate#c_ydmk92)

> My issue with [that](https://lobste.rs/s/wei3a9/downvote_category_for_inappropriate#c_whp49v) categorising is that often, the latter is not trolling; full of references, deconstructions, counterpoints, etc. It’s just slathered in insults and venom. Look, I’m not saying “everyone’s polite” is the perfect community and there’s absolutely nothing wrong with it. You do lose something by enforcing civility. But the rudeness is okay niche is already filled by HN, proggit, and Facebook, and I think keeping lobsters “nice” is more in line with it’s unique values than not.
— [hwayne](https://lobste.rs/s/wei3a9/downvote_category_for_inappropriate#c_qqcycg)

> Your perception that the comment is hostile is also subjective. I prefer that downvotes are reserved for objectively undesirable material. So if someone holds a subjective opinion you do not like, you can ignore that comment and move on. There is no need to attack it with comments or downvotes.
— [duclare](https://lobste.rs/s/wei3a9/downvote_category_for_inappropriate#c_oq2y0m)

> The term troll has a long history of use online, I’d encourage you to become more comfortable with the label as a description of acting in bad faith. The nature of abuse online, particularly in technical communities, is that strictly operational (objective) definitions of the behavior will lead to bickering over irrelevant details. It can all be described as trolling and the issue then put aside.
— [alynpost](https://lobste.rs/s/wei3a9/downvote_category_for_inappropriate#c_pryqvi)

> Downvotes are an appropriate mechanism for comments that “aren’t even wrong.” If I were going to do more than downvote comments as first troll and then off-topic (should a belligerent user persist) it would be to clarify which part of the article they’re replying to. Folk should comment on the material presented, not parrot a talking point that could be trotted out for any article discussing a controversial topic.
— [alynpost](https://lobste.rs/s/wei3a9/downvote_category_for_inappropriate#c_wyjdlg)

There have been many suggestions for what word to use for this new category, most of them as replies to [this post](https://lobste.rs/s/wei3a9/downvote_category_for_inappropriate#c_38yddb). The ones that seem to have gotten the most traction are:

 - uncharitable
 - destructive
 - unconstructive

There was also a discussion in a [separate thread](https://lobste.rs/s/nkxia1/how_use_downvotes_correctly) that raised another way of mitigating this problem:

> A workflow would be a great compromise. Facebook does this pretty well when reporting posts, e.g. “This post is about me” or “This post is about someone else” and “This post is threatening me” or “This post is threatening someone else”.
> 
> Maybe instead of Lobsters offering these short labels, the options could be worded as such:
> 
>  - This comment is unrelated to the original post or anything else in this thread.
>  - This comment is factually or logically incorrect in a blatantly obvious way.
>  - This comment adds no value to the thread beyond expressing “me, too” in some way.
>  - This comment is inflammatory or baiting an argument with no intention of encouraging honest discussion.
>  - This comment is adds no value, contains only an irrelevant link, is low-effort, or commercial in nature
— [colindean](https://lobste.rs/s/nkxia1/how_use_downvotes_correctly#c_cprwww)

---

**My own subjective thoughts**: This debate is clearly something many lobsters care about, and prime among the concerns are that this would encourage mono-culture and "hive-mind thinking" through censorship and "downvote to disagree"-type comment stifling. Inevitably, adding a downvote category that is on the face of it subjective faces that problem. However, I think it is fully possible to have a downvote system that discourages inflammatory and overly-aggressive *writing*, without penalizing or otherwise passing moral judgement on the *contents* of that post. 

I believe that the way to assuage this particular fear is to make sure that the wording of the categories is such that they are hard to misuse. A good start would be to follow [colindean](https://lobste.rs/s/nkxia1/how_use_downvotes_correctly#c_cprwww)'s suggestion of having text for the categories instead of just a one-word tag. We could then introduce a "category" for My proposal (slightly modified from those given in the linked comment) would be the following:

 - This comment is unrelated to the contents of the original post. **(off-topic)**
 - This comment is verifiably factually or logically incorrect. **(incorrect)**
 - This comment could be entirely replaced with "me too". **(me-too)**
 - This comment contains no new information that contributes to the surrounding discussion. **(troll)**
 - This comment is written in a destructive, uncharitable, and inflammatory tone. **(tone)**
 - This comment contains advertisements, malicious links, or otherwise commercial content. **(spam)**

**Comment by jcs** [comment]
I don't think the UI (especially on mobile) will work well with long descriptions instead of one-word names. Those could certainly be added to the Wiki to help people understand how to use them, though.

From your new descriptions, it sounds like troll and me-too could be combined because they both don't add anything useful, but troll definitely has a more negative tone which sounds more like your description for tone.

Why not just replace troll with something more broad like "unconstructive"?  It would probably also help with the meta-discussions when someone accumulates a few troll downvotes and then gets bent out of shape because they're being labeled a troll.

**Comment by jonhoo** [comment]
If, when downvoting, you got a set of screen-width buttons, then I think the full labels could work, but I don't feel too strongly about that.

I agree that the descriptions above make `me-too` and `troll` seem similar, but I'm hesitant about combining them. I think there are a number of posts that could be downvoted as `me-too`, but where I'd be very hesitant to downvote them as `troll`. On the other hand `unconstructive` I feel like *does* cover both `me-too` and `troll`, but is not alone sufficient to target inflammatory posts. Consider a post that contains facts pertinent to the discussion, but that also includes statements like "Clearly you're a f**king moron for not realizing that. Only idiots would think that X is better than Y, as I believe I've just shown". While I suppose such a comment *could* be labeled as `unconstructive` that still feels like a stretch if it does in fact also present relevant logic and facts. This is the reason I wanted `tone` as a separate category. I don't know if the single word `tone` is sufficient to capture that without also bringing with it a whole host of other "downvote because I disagree" type things (hence the use of *and* in the long version), but it's the closest word I could think of.

**Comment by MattCheely** [comment]
In the traditon of naming things being one of the hard problems, I'll
say that while I'm not opposed to the concenpt, I'm not a big fan of 
`tone` as a name, due to negative connotations around "tone policing."
I suspect that would lead to more meta-argument than something like
uncharitable/inflamatory. 

In case it's hepful to enumerate them, here are the trade offs as I see them for just `nonconstructive` vs `nonconstructive` and `tone` (or whatever):

Just `nonconstructive`:
    + Reduces categories by combining me-too & troll
    + Captures rants and other non-contributing content
    + Likely to result in less meta-griping than "troll"
    - Provides a potential out for hostile behavior "but look, I made a suggestion"
    - Could lead to meta-argument about whether uncharitable/dismissive  
        comments can be constructive.

`nonconstructive` & `tone`
    + Makes the purpose of `nonconstructive` clearer by separating it from `tone`
    + Makes it harder to geneate excuses for unfriendly/unwelcoming behavior
    + Lends itself to less bikeshedding about definitions and good/bad faith than 
        nonconstructive/troll since it explicitly casts a wider net.  
    - Has a greater appearance of subjectivity.
    - More likely to be a sticking point / meta-discussion generator for folks who like to rant

**Comment by jcs** [comment]
Seems like we never reached consensus on this...

**Comment by pushcx** [comment]
I think there's conspicuous bikeshedding about the right name for it, but the strong balance of the meta thread was in favor. (Of course, I am strongly in favor, so I *would* think that.) It seems like in the meantime the folks who most wanted this as an explicit downvote option are content to (ab?)use 'Troll' for this.

For completeness's sake, a related meta thread from angersock (who disagrees with the proposal): https://lobste.rs/s/nkxia1/how_use_downvotes_correctly

**Comment by jcs** [comment]
So what is the agreed-upon name for the new downvote option?

**Comment by jcs** [comment]
:man_shrugging:

**Comment by jonhoo** [comment]
@jcs I don't think this is a case where full consensus will be achieved on exactly what the wording should be. It will require a decision to be made (probably by you) about what is most reasonable. I think there *is* strong consensus about this change happening though.
