### ISSUE TITLE
Upfloats are sometimes NaN

### ISSUE THREAD

**Issue by skade** [jcs/lobsters#384]
Upvoting may sometimes lead to "NaN" being displayed where the number (or the "-") should be.

Platform: iPhone with iOS 10, Firefox Browser.

![argorak_2017-jul-27](https://user-images.githubusercontent.com/47542/28665880-72c66b94-72c5-11e7-90ed-e50811f8f0db.jpg)

**Comment by asthasr** [comment]
Seeing the same thing on macOS 10.12.5, Firefox 54.0.1.

**Comment by jcs** [comment]
fixed
