### ISSUE TITLE
NOT IN SUBQUERIES in CommentsController.index

### ISSUE THREAD

**Issue by lelelelemon** [jcs/lobsters#389]
In CommentsController.index,
@comments = @comments.where("story_id NOT IN (SELECT story_id FROM " <<
        "hidden_stories WHERE user_id = ?)", @user.id)
will issue a query like:
SELECT  `comments`.* FROM `comments`  WHERE (story_id NOT IN (SELECT story_id FROM hidden_stories WHERE user_id = 1))

which is costful under mysql, it should be separated into two queries as:
hidden_stories = SELECT story_id FROM hidden_stories WHERE user_id = 1
SELECT  `comments`.* FROM `comments`  WHERE (story_id NOT IN (hidden_stories))
will make the performance better

**Comment by pstef** [comment]
This could be WHERE NOT EXISTS (...) if MySQL supports it.

**Comment by pstef** [comment]
Are there indexes on hidden_stories.story_id and comments.story_id?

**Comment by talklittle** [comment]
I think so:

https://github.com/jcs/lobsters/blob/1f5d2d4587facf32871e972bf50c08701116f190/db/migrate/20150211170052_move_hidden_votes_to_hidden_story.rb#L8

https://github.com/jcs/lobsters/blob/1f5d2d4587facf32871e972bf50c08701116f190/db/schema.rb#L35

**Comment by pstef** [comment]
Those look like multicolumn indexes. I don't know MySQL / MariaDB, but I don't expect them to utilize the indexes for the NOT EXISTS part.

**Comment by talklittle** [comment]
> MySQL can use multiple-column indexes for queries that test all the columns in the index, or queries that test just the first column, the first 2 columns, the first 3 columns, and so on. If you specify the columns in the right order in the index definition, a single composite index can speed up several kinds of queries on the same table.

https://dba.stackexchange.com/questions/12618/when-to-create-multiple-column-index

**Comment by pstef** [comment]
Is it able to tell what indexes are used for a query like this?

    SELECT  `comments`.* FROM `comments`
    WHERE `comments`.`is_deleted` = 0 AND `comments`.`is_moderated` = 0
    AND (NOT EXISTS (SELECT 1 FROM hidden_stories WHERE hidden_stories.user_id = 1
      AND hidden_stories.story_id = comments.story_id))
    ORDER BY id DESC LIMIT 20 OFFSET 0

Anyway, I would say that NOT EXISTS is the canonical SQL way to do this since it'll work as expected regardless of whether hidden_stories.story_id can be NULL or not - while the NOT IN version doesn't give that guarantee.

And certainly, two independent is not the way to go.
