### ISSUE TITLE
ModerationsController.index has N + 1 queries

### ISSUE THREAD

**Issue by lelelelemon** [jcs/lobsters#390]
when retrieve moderations from database, the moderator,  story, and related comment should be eager loaded together, or else there will be N + 1 queries.

@moderations = Moderation.includes(:user, :moderator, :comment, :story, comment: :story).order("id desc").limit(50).offset((@page - 1) *
      50)

**Comment by pushcx** [comment]
The gem `bullet` is excellent for catching these in dev/test mode.
