### ISSUE TITLE
count > 0 could be exists

### ISSUE THREAD

**Issue by lelelelemon** [jcs/lobsters#393]
https://github.com/jcs/lobsters/blob/505c89ec45b3e872d359c1af5cf285d657bc159b/app/helpers/stories_helper.rb#L13
change count > 0 to exists should reduce some time cost on this join query. 

Also, from the user perspective, I don't mind whether you show me the guidelines or not, you can always show it there, without getting result from show_guidelines?

**Comment by pushcx** [comment]
Showing the guidelines means the user has to scroll to click the submit button, which is annoying after a few dozen times when they're well-understood.

**Comment by jcs** [comment]
Why don't you submit pull requests for these?

**Comment by lelelelemon** [comment]
will do, just confirm they are right

**Comment by talklittle** [comment]
My unscientific tests showed that this seems to work. The original query on my machine is usually 0.4 - 0.6ms, after changing to `exists?` it's usually 0.3 - 0.5 ms.

Original

    (0.6ms)  SELECT COUNT(*) FROM `moderations` INNER JOIN `stories` ON `stories`.`id` = `moderations`.`story_id` WHERE (stories.user_id = 1 AND moderations.created_at > '2017-09-10 04:24:30.787520')

New

    Moderation Exists (0.4ms)  SELECT  1 AS one FROM `moderations` INNER JOIN `stories` ON `stories`.`id` = `moderations`.`story_id` WHERE (stories.user_id = 1 AND moderations.created_at > '2017-09-10 04:26:56.834892') LIMIT 1

**Comment by talklittle** [comment]
@lelelelemon I'm probably going to submit a PR for this soon, unless you do in the next few days. Let us know!
