### ISSUE TITLE
Delete Invitation needs reason, moderation log entry, and feedback to user

### ISSUE THREAD

**Issue by mozboz** [jcs/lobsters#395]
I occasionally check the invite queue and on occasion I want to delete the invitation, for a reason like the URL given is not available or it's a business or spammy blog and I want to see a little bit of personal information to give the invite.

When I delete the invitation, I don't have the opportunity to give some feedback to the user, or to give a reason as to why the invite was deleted, which is a loss of useful information; it seems like it would be great to be able to write a few words why the invite was deleted, if it's a real person they can reapply with a fixed/better url.

Also I want the reason I delete the invitation to be public and accountable, otherwise this feature is too much power for non admin users.

**Comment by jcs** [comment]
We don’t owe spammers anything
