### ISSUE TITLE
comment collapse buttons visible on single comments

### ISSUE THREAD

**Issue by jcs** [jcs/lobsters#408]
@talklittle On https://lobste.rs/comments the collapse buttons should not be visible.  Something in the thread lines commits changed this.

**Comment by talklittle** [comment]
I'll look into that and also add the lines as appropriate to https://lobste.rs/threads

**Comment by jcs** [comment]
Thanks.  BTW, I am rebasing all of these commits into one on master, so you'll probably need to rebase your fork.
